//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUNGER_ZERO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollectRequest()
        {
            this.CollectRequest1 = new HashSet<CollectRequest>();
        }
    
        public System.Guid CollectRequestId { get; set; }
        public System.Guid RestaurantId { get; set; }
        public System.Guid EmployeeId { get; set; }
        public System.DateTime RequestedTime { get; set; }
        public System.DateTime MaxPreservationTime { get; set; }
        public string CompletionStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectRequest> CollectRequest1 { get; set; }
        public virtual CollectRequest CollectRequest2 { get; set; }
    }
}
